runtime: php74 # Replace with php74 to use PHP 7.4

runtime_config:
  document_root: .

handlers:
# Serve as static resources.
- url: /(.+\.(php|css|js|jpeg|jpg|png))$
  static_files: \1
  upload: .+\.(php|css|js|jpeg|jpg|png)$

# Serve your app through a front controller at index.php or public/index.php.
- url: /.*
  script: auto
 
entrypoint:
  serve handler.php
   
env_variables:
  CLOUDSQL_USER: sql12395648
  CLOUDSQL_PASSWORD: dWTrM7792J
  CLOUDSQL_DSN: "mysql:host=sql12.freemysqlhosting.net; port=3306; dbname=sql12395648;unix_socket=/cloudsql/happy-pals:asia-southeast2:happy-pals-my-sql"